const fs = require('fs'), vm = require('vm'), assert = require('assert/strict'), ts = require('typescript');
const root = 'src/components/inputs/';
const compile = s => ts.transpileModule(s, { compilerOptions: { target: 7, module: 1, jsx: 4 } }).outputText;
function focus(os) { const calls = [], input = { tag: 10 }; const exports = {}; const doc = { activeElement: { closest: () => true, blur: () => calls.push('blur') } }; vm.runInNewContext(compile(fs.readFileSync(root + 'keyboard-focus.ts', 'utf8')), { exports, document: doc, require: () => ({ Platform: { OS: os }, findNodeHandle: x => x.tag, Keyboard: { dismiss: () => calls.push('dismiss') }, TextInput: { State: { currentlyFocusedInput: () => input } } }) }); return { calls, input, exports }; }
let n = 0;
for (const os of ['android', 'ios']) {
    const t = focus(os);
    t.exports.registerInput(t.input);
    assert.equal(t.exports.dismissOnOutsideTouch({ target: t.input }), false);
    assert.equal(t.calls.length, 0);
    assert.equal(t.exports.dismissOnOutsideTouch({ target: 10 }), false);
    assert.equal(t.calls.length, 0);
    let pressed = 0;
    assert.equal(t.exports.dismissOnOutsideTouch({ target: { tag: 20 } }), false);
    pressed++;
    assert.equal(pressed, 1);
    assert.deepEqual(t.calls, ['dismiss']);
    t.exports.unregisterInput(t.input);
    assert.equal(t.exports.isInputTarget(t.input), false);
    n++;
}
{
    const t = focus('web');
    assert.equal(t.exports.dismissOnOutsideTouch({ target: { closest: () => true } }), false);
    assert.equal(t.calls.length, 0);
    assert.equal(t.exports.dismissOnOutsideTouch({ target: { closest: () => null } }), false);
    assert.deepEqual(t.calls, ['blur']);
    n++;
}
// Exercise wrapper handlers with fake layout/keyboard events, not just source checks.
const nodes = [], contexts = [], listeners = {}, raf = [];
let dismissVisible = true;
const jsx = (type, props) => { const n = { type, props }; nodes.push(n); return n; };
const react = { createContext: value => { const c = { value, Provider: 'Provider' + contexts.length }; contexts.push(c); return c; }, useContext: c => c.value, useRef: value => ({ current: value }), useEffect: fn => fn(), forwardRef: fn => fn };
const native = { Platform: { OS: 'android' }, Keyboard: { addListener: (event, fn) => { listeners[event] = fn; return { remove() { } }; }, isVisible: () => dismissVisible }, ScrollView: 'ScrollView', TextInput: 'TextInput', Modal: 'Modal', KeyboardAvoidingView: 'KeyboardAvoidingView' };
const moduleOut = {};
vm.runInNewContext(compile(fs.readFileSync(root + 'KeyboardAware.tsx', 'utf8')), { exports: moduleOut, require: name => name === 'react' ? react : name === 'react/jsx-runtime' ? { jsx, jsxs: jsx } : name === 'react-native' ? native : name.includes('keyboard-focus') ? { registerInput() { }, unregisterInput() { } } : { __esModule: true, default: 'Boundary' }, requestAnimationFrame: fn => { raf.push(fn); return raf.length; }, cancelAnimationFrame() { } });
let focused = 0, blurred = 0, layout = 0;
const scrollRef = { current: null };
moduleOut.ScrollView({ onLayout: () => layout++, keyboardShouldPersistTaps: 'handled', children: 'form' }, scrollRef);
const scrollNode = nodes.find(n => n.type === 'ScrollView');
const scrollCalls = [];
const scroll = { scrollResponderScrollNativeHandleToKeyboard: (...args) => scrollCalls.push(args) };
scrollNode.props.ref(scroll);
assert.equal(scrollRef.current, scroll);
assert.equal(scrollNode.props.keyboardShouldPersistTaps, 'always');
assert.equal(scrollNode.props.automaticallyAdjustKeyboardInsets, true);
contexts[0].value = nodes.find(n => n.type === contexts[0].Provider).props.value;
const inputRef = { current: null };
moduleOut.TextInput({ value: 'original', onChangeText: () => { }, onFocus: () => focused++, onBlur: () => blurred++ }, inputRef);
const inputNode = nodes.find(n => n.type === 'TextInput');
const input = { isFocused: () => true };
inputNode.props.ref(input);
assert.equal(inputRef.current, input);
inputNode.props.onFocus({});
raf.splice(0).forEach(fn => fn());
assert.equal(focused, 1);
assert.equal(scrollCalls.length, 1);
assert.equal(scrollCalls[0][0], input);
listeners.keyboardDidShow();
raf.splice(0).forEach(fn => fn());
assert.equal(scrollCalls.length, 2);
scrollNode.props.onLayout({});
raf.splice(0).forEach(fn => fn());
assert.equal(layout, 1);
assert.equal(scrollCalls.length, 3);
inputNode.props.onBlur({});
raf.splice(0).forEach(fn => fn());
assert.equal(blurred, 1);
assert.equal(scrollCalls.length, 3);
assert.equal(inputNode.props.value, 'original');
n++;
contexts[1].value = true;
nodes.length = 0;
moduleOut.ScrollView({ children: 'existing KAV' }, null);
assert.equal(nodes.find(n => n.type === 'ScrollView').props.automaticallyAdjustKeyboardInsets, false);
n++;
nodes.length = 0;
moduleOut.Modal({ visible: true, transparent: true, onRequestClose() { }, children: 'dialog' });
assert.equal(nodes.find(n => n.type === 'Modal').props.transparent, true);
assert.equal(nodes.find(n => n.type === contexts[1].Provider).props.value, false);
assert.ok(nodes.some(n => n.type === 'Boundary'));
n++;
console.log(`${n} keyboard scenarios passed: native/web outside taps, input switching, first-tap delivery, focus scrolling, forwarded refs/handlers, existing keyboard layouts and modal boundaries.`);
