-- Rollback-only fixtures. No workshop record survives this script.
BEGIN;
DO $test$
DECLARE advisor uuid; floor_user uuid; store_user uuid; v uuid:=gen_random_uuid(); w uuid:=gen_random_uuid(); j uuid:=gen_random_uuid(); c uuid; a uuid; first_cycle uuid; req uuid; order_id uuid; path text; denied boolean; q jsonb; before_count integer;
BEGIN
  SELECT id INTO advisor FROM public.profiles WHERE role='advisor' AND is_active LIMIT 1;
  SELECT id INTO floor_user FROM public.profiles WHERE role='floor_incharge' AND is_active LIMIT 1;
  SELECT id INTO store_user FROM public.profiles WHERE role='store_team' AND is_active LIMIT 1;
  INSERT INTO public.vehicles(id,vehicle_no,current_stage,current_status,current_assigned_to) VALUES(v,'SUPTEST-'||left(v::text,8),'FLOOR','PENDING',advisor);
  INSERT INTO public.workshop_visits(id,vehicle_id,visit_no,current_stage,current_status,current_assigned_to) VALUES(w,v,1,'FLOOR','PENDING',advisor);
  INSERT INTO public.vehicle_jobs(id,vehicle_id,advisor_id,job_type,current_job_stage,approval_status) VALUES(j,v,advisor,'PAID','FLOOR','APPROVED');
  INSERT INTO public.vehicle_assignments(visit_id,vehicle_id,assigned_to,assigned_by,assignment_role,assigned_at) VALUES(w,v,advisor,advisor,'ADVISOR',now());
  INSERT INTO public.workflow_stage_history(visit_id,vehicle_id,stage,entered_at,entered_by,status) VALUES(w,v,'FLOOR',now(),advisor,'OPEN');
  INSERT INTO public.advisor_work(visit_id,vehicle_id,work_path,parts_required,denting_required,painting_required,assigned_by) VALUES(w,v,'ONLY_DENTING_PAINTING',false,true,true,advisor);
  INSERT INTO public.approval_cycles(visit_id,vehicle_id,cycle_no,cycle_type,decision,approval_received_at,decided_by) VALUES(w,v,1,'INITIAL','APPROVED',now(),advisor);
  PERFORM set_config('request.jwt.claim.sub',advisor::text,true);
  PERFORM public.new_workflow_prepare_floor(w,floor_user);
  denied:=false; BEGIN PERFORM public.new_workflow_prepare_floor(w,floor_user); EXCEPTION WHEN OTHERS THEN denied:=true; END;
  IF NOT denied THEN RAISE EXCEPTION 'Duplicate Floor cycle accepted'; END IF;
  PERFORM set_config('request.jwt.claim.sub',floor_user::text,true);
  PERFORM public.new_workflow_start_stripping(w);
  denied:=false; BEGIN PERFORM public.new_workflow_request_supplementary(w,' '); EXCEPTION WHEN OTHERS THEN denied:=true; END;
  IF NOT denied THEN RAISE EXCEPTION 'Blank reason accepted'; END IF;
  path:='vehicles/'||v||'/SUPPLEMENTARY/'||w||'/DISCOVERY/test.jpg';
  INSERT INTO storage.objects(bucket_id,name,owner_id) VALUES('vehicle-photos',path,floor_user::text);
  c:=(public.new_workflow_request_supplementary(w,'Additional damage found',path)->>'supplementary_cycle_id')::uuid; first_cycle:=c;
  IF (SELECT current_job_stage FROM public.vehicle_jobs WHERE id=j)<>'ADVISOR' THEN RAISE EXCEPTION 'Job stage not synchronized'; END IF;
  denied:=false; BEGIN PERFORM public.new_workflow_request_supplementary(w,'Double submit'); EXCEPTION WHEN OTHERS THEN denied:=true; END;
  IF NOT denied THEN RAISE EXCEPTION 'Duplicate request accepted'; END IF;
  PERFORM set_config('request.jwt.claim.sub',advisor::text,true);
  PERFORM public.new_workflow_complete_supplementary_survey(c,now());
  SELECT approval_cycle_id INTO a FROM public.supplementary_cycles WHERE id=c;
  q:=public.new_workflow_supplementary_queue(false);
  IF NOT EXISTS(SELECT 1 FROM jsonb_array_elements(q->'items') x WHERE x->>'visit_id'=w::text AND jsonb_array_length(x->'cycle_history')=1 AND jsonb_array_length(x->'evidence')=1) THEN RAISE EXCEPTION 'Queue history/evidence missing'; END IF;
  denied:=false; BEGIN PERFORM public.new_workflow_process_approval(w,'APPROVED',now()); EXCEPTION WHEN OTHERS THEN denied:=true; END;
  IF NOT denied THEN RAISE EXCEPTION 'Initial Approval consumed Supplementary'; END IF;
  denied:=false; BEGIN PERFORM public.new_workflow_decide_supplementary(c,'TOTAL_LOSS',now()); EXCEPTION WHEN OTHERS THEN denied:=true; END;
  IF NOT denied THEN RAISE EXCEPTION 'Unapproved decision accepted'; END IF;
  denied:=false; BEGIN PERFORM public.new_workflow_decide_supplementary(c,'APPROVED',now()); EXCEPTION WHEN OTHERS THEN denied:=true; END;
  IF NOT denied THEN RAISE EXCEPTION 'Approval without proof accepted'; END IF;
  path:='vehicles/'||v||'/SUPPLEMENTARY/'||w||'/ASSIGNMENT/test-hold.jpg';
  INSERT INTO storage.objects(bucket_id,name,owner_id) VALUES('vehicle-photos',path,advisor::text);
  PERFORM public.new_workflow_decide_supplementary(c,'APPROVAL_HOLD',now(),'Awaiting insurer',path);
  PERFORM public.new_workflow_resolve_approval_hold(w);
  IF (SELECT current_stage FROM public.workshop_visits WHERE id=w)<>'PENDING_APPROVAL' OR (SELECT status FROM public.supplementary_cycles WHERE id=c)<>'APPROVAL' THEN RAISE EXCEPTION 'Resolve state mismatch'; END IF;
  path:='vehicles/'||v||'/SUPPLEMENTARY/'||w||'/ASSESSMENT/test-approve.jpg';
  INSERT INTO storage.objects(bucket_id,name,owner_id) VALUES('vehicle-photos',path,advisor::text);
  PERFORM public.new_workflow_decide_supplementary(c,'APPROVED',now(),NULL,path,false);
  IF (SELECT count(*) FROM public.approval_cycles WHERE visit_id=w)<>2 OR (SELECT approval_hold_remark FROM public.approval_cycles WHERE id=a)<>'Awaiting insurer' OR (SELECT current_stage FROM public.workshop_visits WHERE id=w)<>'FLOOR' THEN RAISE EXCEPTION 'Same-cycle preservation/return failed'; END IF;
  PERFORM set_config('request.jwt.claim.sub',floor_user::text,true); PERFORM public.new_workflow_start_stripping(w);
  PERFORM set_config('request.jwt.claim.sub',advisor::text,true);
  c:=(public.new_workflow_request_supplementary(w,'Second supplementary')->>'supplementary_cycle_id')::uuid;
  PERFORM public.new_workflow_complete_supplementary_survey(c,now(),NULL,125,NULL);
  PERFORM public.new_workflow_decide_supplementary(c,'CLAIM_REJECTED',now(),'Insurer rejected extra scope');
  PERFORM public.new_workflow_continue_without_supplementary(c);
  IF (SELECT status FROM public.supplementary_cycles WHERE id=c)<>'CONTINUED_WITHOUT_SUPPLEMENTARY' OR (SELECT decision FROM public.approval_cycles WHERE id=(SELECT approval_cycle_id FROM public.supplementary_cycles WHERE id=c))<>'CLAIM_REJECTED' THEN RAISE EXCEPTION 'Rejection continuation failed'; END IF;
  PERFORM set_config('request.jwt.claim.sub',floor_user::text,true); PERFORM public.new_workflow_start_stripping(w);
  PERFORM set_config('request.jwt.claim.sub',advisor::text,true);
  c:=(public.new_workflow_request_supplementary(w,'Third supplementary: extra parts')->>'supplementary_cycle_id')::uuid;
  PERFORM public.new_workflow_complete_supplementary_survey(c,now(),NULL,NULL,'Optional receipt only');
  path:='vehicles/'||v||'/SUPPLEMENTARY/'||w||'/ASSESSMENT/test-parts.jpg';
  INSERT INTO storage.objects(bucket_id,name,owner_id) VALUES('vehicle-photos',path,advisor::text);
  PERFORM public.new_workflow_decide_supplementary(c,'APPROVED',now(),NULL,path,true);
  req:=(public.new_workflow_supplementary_parts(c,'DENTING_PAINTING_PARTS','SUP-REQ-TEST',now())->>'part_requisition_id')::uuid;
  IF (SELECT count(*) FROM public.advisor_work WHERE visit_id=w)<>1 THEN RAISE EXCEPTION 'Original Advisor Work duplicated'; END IF;
  PERFORM set_config('request.jwt.claim.sub',store_user::text,true);
  order_id:=(public.new_workflow_create_part_order(w,'SUP-ORDER-TEST','REGULAR',now())->>'part_order_id')::uuid;
  PERFORM public.new_workflow_receive_parts(order_id,now());
  PERFORM public.new_workflow_hand_over_parts_to_floor(order_id,floor_user,now());
  IF (SELECT status FROM public.supplementary_cycles WHERE id=c)<>'RETURNED_TO_FLOOR' OR (SELECT current_job_stage FROM public.vehicle_jobs WHERE id=j)<>'FLOOR' THEN RAISE EXCEPTION 'Parts handover return failed'; END IF;
  IF (SELECT count(*) FROM public.floor_work_cycles WHERE visit_id=w AND status='ACTIVE')<>1 OR (SELECT count(*) FROM public.workflow_stage_history WHERE visit_id=w AND status='OPEN')<>1 THEN RAISE EXCEPTION 'Multiple active cycles/stages'; END IF;
  IF (SELECT approval_status FROM public.vehicle_jobs WHERE id=j)<>'APPROVED' THEN RAISE EXCEPTION 'Initial approved scope changed'; END IF;
  IF (SELECT count(*) FROM public.supplementary_cycles WHERE visit_id=w)<>3 OR (SELECT count(*) FROM public.approval_cycles WHERE visit_id=w)<>4 THEN RAISE EXCEPTION 'Repeated cycle numbering incorrect'; END IF;
  SELECT count(*) INTO before_count FROM public.workflow_events WHERE visit_id=w;
  denied:=false; BEGIN PERFORM public.new_workflow_request_supplementary(w,'Unauthorized Store request'); EXCEPTION WHEN OTHERS THEN denied:=true; END;
  IF NOT denied OR (SELECT count(*) FROM public.workflow_events WHERE visit_id=w)<>before_count THEN RAISE EXCEPTION 'Unauthorized operation wrote audit rows'; END IF;
  SET LOCAL ROLE authenticated;
  IF EXISTS(SELECT 1 FROM public.supplementary_cycles WHERE visit_id=w) THEN RAISE EXCEPTION 'Store user can read restricted supplementary rows'; END IF;
  PERFORM set_config('request.jwt.claim.sub',advisor::text,true);
  IF (SELECT count(*) FROM public.supplementary_cycles WHERE visit_id=w)<>3 THEN RAISE EXCEPTION 'Assigned Advisor cannot read cycle history'; END IF;
  IF (SELECT count(*) FROM public.floor_work_items i JOIN public.floor_work_cycles f ON f.id=i.floor_work_cycle_id WHERE f.visit_id=w)=0 THEN RAISE EXCEPTION 'Assigned Advisor Floor history missing'; END IF;
  PERFORM set_config('request.jwt.claim.sub','',true);
  denied:=false; BEGIN PERFORM public.new_workflow_supplementary_queue(false); EXCEPTION WHEN OTHERS THEN denied:=true; END;
  IF NOT denied THEN RAISE EXCEPTION 'Missing session accepted'; END IF;
END;
$test$;
ROLLBACK;
SELECT 'PASS: three cycles, same-cycle Hold/Resolve, optional Paid fields/photos, rejection continuation, extra-parts Store handover, role/RLS checks, duplicate/invalid submissions, history and job preservation. All fixtures rolled back.' AS result;
