import { StyleSheet } from "react-native";
import { colors, spacing, typography } from "../src/theme";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  loadingContainer: {
    flex: 1,
    backgroundColor: colors.background,
    justifyContent: "center",
    alignItems: "center",
  },
  loadingContent: {
    alignItems: "center",
    padding: 30,
  },
  loadingLogo: {
    width: 58,
    height: 58,
    borderRadius: 20,
    backgroundColor: colors.primary,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 22,
  },
  loadingLogoText: {
    color: "#FFFFFF",
    fontSize: 30,
    fontWeight: "900",
  },
  loadingTitle: {
    marginTop: 18,
    color: colors.text,
    fontSize: 17,
    fontWeight: "800",
  },
  loadingSubtitle: {
    marginTop: 7,
    color: colors.textSecondary,
    fontSize: 13,
  },
  content: {
    padding: spacing.lg,
    paddingBottom: spacing.xxl + 10,
  },
  topBar: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: spacing.lg,
  },
  backButton: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 8,
    paddingRight: 10,
  },
  backArrow: {
    color: colors.primary,
    fontSize: 27,
    lineHeight: 28,
    marginRight: 5,
  },
  back: {
    ...typography.bodyMedium,
    color: colors.primary,
    fontWeight: "700",
  },
  brandMark: {
    fontWeight: "900",
    letterSpacing: 1.8,
    color: colors.text,
    fontSize: 13,
  },

  // Hero area
  hero: {
    backgroundColor: colors.primary,
    borderRadius: 26,
    padding: 20,
    marginBottom: 16,
    overflow: "hidden",
    shadowColor: "#10234A",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.17,
    shadowRadius: 16,
    elevation: 6,
  },
  heroTopRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 8,
  },
  workspacePill: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(255,255,255,0.13)",
    borderRadius: 30,
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  onlineDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: "#85F0BC",
    marginRight: 7,
  },
  eyebrow: {
    color: "#E4ECFF",
    fontSize: 10,
    fontWeight: "900",
    letterSpacing: 1.2,
  },
  livePill: {
    borderRadius: 30,
    paddingHorizontal: 10,
    paddingVertical: 7,
    backgroundColor: "rgba(255,255,255,0.13)",
  },
  livePillText: {
    color: "#FFFFFF",
    fontSize: 9,
    fontWeight: "900",
    letterSpacing: 0.7,
  },
  completedPill: {
    borderRadius: 30,
    paddingHorizontal: 10,
    paddingVertical: 7,
    backgroundColor: "rgba(108,236,176,0.18)",
    borderWidth: 1,
    borderColor: "rgba(172,255,216,0.28)",
  },
  completedPillText: {
    color: "#B9FFDB",
    fontSize: 9,
    fontWeight: "900",
    letterSpacing: 0.7,
  },
  heading: {
    fontSize: 29,
    fontWeight: "900",
    color: "#FFFFFF",
    marginTop: 18,
    letterSpacing: -0.6,
  },
  subheading: {
    color: "#E2E9F8",
    fontSize: 13,
    lineHeight: 20,
    marginTop: 7,
    maxWidth: 340,
  },
  vehicleHeroCard: {
    marginTop: 20,
    backgroundColor: "rgba(255,255,255,0.12)",
    borderRadius: 18,
    padding: 13,
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.14)",
    gap: 12,
  },
  vehicleIconBox: {
    width: 48,
    height: 48,
    borderRadius: 15,
    backgroundColor: "rgba(255,255,255,0.16)",
    alignItems: "center",
    justifyContent: "center",
  },
  vehicleIcon: {
    fontSize: 25,
  },
  vehicleHeroCopy: {
    flex: 1,
    minWidth: 0,
  },
  regLabel: {
    fontSize: 9,
    fontWeight: "900",
    letterSpacing: 1.1,
    color: "#C9D8F7",
  },
  regNumber: {
    fontSize: 22,
    fontWeight: "900",
    color: "#FFFFFF",
    marginTop: 4,
    letterSpacing: 0.4,
  },
  vehicleCustomer: {
    fontSize: 12,
    color: "#F4F7FF",
    fontWeight: "700",
    marginTop: 5,
  },
  vehicleMeta: {
    fontSize: 11,
    color: "#CFDAF0",
    marginTop: 4,
  },
  assignedBadge: {
    backgroundColor: "rgba(255,255,255,0.17)",
    borderRadius: 7,
    paddingHorizontal: 7,
    paddingVertical: 5,
    alignSelf: "flex-start",
  },
  assignedBadgeText: {
    fontSize: 8,
    color: "#FFFFFF",
    fontWeight: "900",
    letterSpacing: 0.5,
  },

  // Progress card
  progressCard: {
    backgroundColor: colors.surface,
    borderRadius: 18,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: colors.border,
  },
  progressHeadingRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 10,
  },
  progressTitle: {
    fontSize: 15,
    fontWeight: "900",
    color: colors.text,
  },
  progressSubtitle: {
    fontSize: 11,
    color: colors.textSecondary,
    marginTop: 4,
  },
  progressCountPill: {
    backgroundColor: colors.background,
    borderRadius: 9,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  progressCountText: {
    fontSize: 11,
    color: colors.primary,
    fontWeight: "900",
  },
  progressTrack: {
    height: 6,
    backgroundColor: colors.background,
    borderRadius: 20,
    overflow: "hidden",
    marginTop: 15,
  },
  progressFill: {
    height: "100%",
    borderRadius: 20,
    backgroundColor: colors.primary,
  },
  progressLabels: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 9,
  },
  progressLabelActive: {
    fontSize: 9,
    color: colors.primary,
    fontWeight: "800",
  },
  progressLabel: {
    fontSize: 9,
    color: colors.textLight,
    fontWeight: "600",
  },

  // General cards and section headings
  card: {
    backgroundColor: colors.surface,
    borderRadius: 22,
    padding: 18,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: colors.border,
    shadowColor: "#172B4D",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.045,
    shadowRadius: 10,
    elevation: 2,
  },
  sectionHeading: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 18,
    gap: 11,
  },
  sectionNumber: {
    width: 39,
    height: 39,
    borderRadius: 13,
    backgroundColor: colors.background,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: "center",
    justifyContent: "center",
  },
  sectionNumberText: {
    color: colors.primary,
    fontSize: 12,
    fontWeight: "900",
  },
  sectionHeadingCopy: {
    flex: 1,
  },
  cardTitle: {
    fontSize: 17,
    fontWeight: "900",
    color: colors.text,
    letterSpacing: -0.25,
  },
  sectionSubtitle: {
    color: colors.textSecondary,
    fontSize: 11,
    lineHeight: 16,
    marginTop: 4,
  },
  sectionTitle: {
    fontSize: 15,
    fontWeight: "900",
    color: colors.text,
    marginTop: 23,
    marginBottom: 12,
  },

  // Customer and vehicle panels
  customerPanel: {
    flexDirection: "row",
    alignItems: "center",
    padding: 13,
    borderRadius: 16,
    backgroundColor: colors.background,
    borderWidth: 1,
    borderColor: colors.border,
    gap: 12,
  },
  customerAvatar: {
    width: 46,
    height: 46,
    borderRadius: 16,
    backgroundColor: colors.primary,
    alignItems: "center",
    justifyContent: "center",
  },
  customerAvatarText: {
    color: "#FFFFFF",
    fontSize: 20,
    fontWeight: "900",
  },
  customerPanelCopy: {
    flex: 1,
    minWidth: 0,
  },
  detailLabel: {
    color: colors.textSecondary,
    fontSize: 9,
    fontWeight: "900",
    letterSpacing: 0.9,
  },
  customerName: {
    color: colors.text,
    fontSize: 16,
    fontWeight: "900",
    marginTop: 5,
  },
  customerMobile: {
    color: colors.textSecondary,
    fontSize: 12,
    marginTop: 4,
  },
  registrationPanel: {
    borderRadius: 16,
    padding: 15,
    backgroundColor: colors.background,
    borderWidth: 1,
    borderColor: colors.border,
  },
  registrationNumberLarge: {
    fontSize: 24,
    fontWeight: "900",
    letterSpacing: 0.6,
    color: colors.text,
    marginTop: 7,
  },
  vehicleTagRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
    gap: 7,
    marginTop: 12,
  },
  vehicleTag: {
    paddingHorizontal: 9,
    paddingVertical: 6,
    borderRadius: 8,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
  },
  vehicleTagText: {
    fontSize: 10,
    color: colors.text,
    fontWeight: "800",
  },
  stageTag: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    paddingHorizontal: 9,
    paddingVertical: 6,
    borderRadius: 8,
    backgroundColor: "rgba(35,170,112,0.09)",
  },
  stageDot: {
    width: 5,
    height: 5,
    borderRadius: 3,
    backgroundColor: "#21A875",
  },
  stageTagText: {
    fontSize: 9,
    color: "#16865C",
    fontWeight: "900",
  },
  detailGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginTop: 12,
    gap: 9,
  },
  detailItem: {
    width: "48%",
    flexGrow: 1,
    minWidth: 110,
    padding: 11,
    borderRadius: 12,
    backgroundColor: colors.background,
  },
  detailValue: {
    color: colors.text,
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "700",
    marginTop: 5,
  },

  // Form fields
  field: {
    marginTop: 13,
  },
  label: {
    fontSize: 12,
    fontWeight: "800",
    color: colors.text,
    marginTop: 14,
    marginBottom: 8,
  },
  required: {
    color: "#E05252",
    fontWeight: "900",
  },
  input: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 13,
    paddingHorizontal: 14,
    paddingVertical: 13,
    fontSize: 14,
    color: colors.text,
    backgroundColor: colors.background,
    marginBottom: 3,
  },
  inputValue: {
    flex: 1,
    fontSize: 14,
    color: colors.text,
    fontWeight: "700",
  },
  placeholderText: {
    color: colors.textLight,
    fontSize: 14,
    flex: 1,
  },
  multiline: {
    minHeight: 105,
    paddingTop: 13,
    lineHeight: 20,
  },
  pressed: {
    opacity: 0.82,
    transform: [{ scale: 0.99 }],
  },
  disabled: {
    opacity: 0.52,
  },
  inlineHint: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 8,
    marginTop: 12,
    padding: 11,
    borderRadius: 11,
    backgroundColor: colors.background,
  },
  inlineHintIcon: {
    fontSize: 15,
    color: colors.primary,
    fontWeight: "900",
  },
  inlineHintText: {
    flex: 1,
    fontSize: 11,
    lineHeight: 17,
    color: colors.textSecondary,
  },

  // Job type selector
  jobTypeRow: {
    gap: 10,
  },
  jobTypeCard: {
    flexDirection: "row",
    alignItems: "center",
    padding: 13,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 15,
    backgroundColor: colors.background,
    gap: 11,
  },
  jobTypeCardSelected: {
    borderColor: colors.primary,
    backgroundColor: "rgba(36,107,253,0.07)",
  },
  jobTypeIconWrap: {
    width: 43,
    height: 43,
    borderRadius: 13,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: "center",
    justifyContent: "center",
  },
  jobTypeIconWrapSelected: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  jobTypeIcon: {
    color: colors.text,
    fontSize: 21,
    fontWeight: "900",
  },
  jobTypeIconSelected: {
    color: "#FFFFFF",
  },
  jobTypeCopy: {
    flex: 1,
  },
  jobTypeTitle: {
    color: colors.text,
    fontSize: 14,
    fontWeight: "900",
  },
  jobTypeTitleSelected: {
    color: colors.primary,
  },
  jobTypeSubtitle: {
    color: colors.textSecondary,
    fontSize: 11,
    marginTop: 4,
  },
  jobTypeSubtitleSelected: {
    color: colors.text,
  },
  radioOuter: {
    width: 20,
    height: 20,
    borderWidth: 1.5,
    borderColor: colors.border,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  radioOuterSelected: {
    borderColor: colors.primary,
  },
  radioInner: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: colors.primary,
  },

  // MI selector and insurance company
  miTypeRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 9,
  },
  miTypeCard: {
    flexDirection: "row",
    alignItems: "center",
    flexGrow: 1,
    flexBasis: "45%",
    minWidth: 115,
    paddingHorizontal: 12,
    paddingVertical: 14,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 13,
    backgroundColor: colors.background,
    gap: 8,
  },
  miTypeCardSelected: {
    borderColor: colors.primary,
    backgroundColor: "rgba(36,107,253,0.07)",
  },
  miTypeIndicator: {
    width: 19,
    height: 19,
    borderRadius: 7,
    borderWidth: 1.5,
    borderColor: colors.border,
    alignItems: "center",
    justifyContent: "center",
  },
  miTypeIndicatorSelected: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  miTypeCheck: {
    fontSize: 12,
    color: "#FFFFFF",
    fontWeight: "900",
  },
  miTypeText: {
    flex: 1,
    fontSize: 12,
    fontWeight: "800",
    color: colors.text,
  },
  miTypeTextSelected: {
    color: colors.primary,
  },
  dropdownTrigger: {
    minHeight: 51,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 13,
    paddingHorizontal: 14,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: colors.background,
    gap: 10,
  },
  dropdownChevron: {
    fontSize: 21,
    color: colors.primary,
    fontWeight: "700",
  },
  dropdownOptions: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 13,
    marginTop: 6,
    overflow: "hidden",
    backgroundColor: colors.surface,
  },
  dropdownOption: {
    paddingHorizontal: 14,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: colors.divider,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  dropdownOptionPressed: {
    backgroundColor: colors.background,
  },
  dropdownOptionText: {
    flex: 1,
    fontSize: 14,
    color: colors.text,
    fontWeight: "600",
  },
  selectedMark: {
    color: colors.primary,
    fontSize: 17,
    fontWeight: "900",
    marginLeft: 10,
  },
  emptyText: {
    fontSize: 12,
    color: colors.textSecondary,
    padding: 14,
  },
  autoSelectedBox: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 14,
    padding: 13,
    backgroundColor: colors.background,
    marginTop: 15,
  },
  autoSelectedIcon: {
    width: 30,
    height: 30,
    borderRadius: 10,
    backgroundColor: "rgba(35,170,112,0.12)",
    alignItems: "center",
    justifyContent: "center",
  },
  autoSelectedCheck: {
    color: "#16865C",
    fontSize: 16,
    fontWeight: "900",
  },
  autoSelectedCopy: {
    flex: 1,
  },
  autoSelectedLabel: {
    fontSize: 10,
    color: colors.textSecondary,
    fontWeight: "800",
  },
  autoSelectedValue: {
    fontSize: 14,
    fontWeight: "900",
    color: colors.text,
    marginTop: 4,
  },
  autoSelectedBadge: {
    backgroundColor: "rgba(35,170,112,0.12)",
    borderRadius: 6,
    paddingHorizontal: 7,
    paddingVertical: 5,
  },
  autoSelectedBadgeText: {
    color: "#16865C",
    fontSize: 8,
    fontWeight: "900",
  },
  helper: {
    fontSize: 11,
    lineHeight: 17,
    color: colors.textSecondary,
    marginTop: 5,
  },

  // Date and time
  dateButton: {
    minHeight: 52,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 13,
    paddingHorizontal: 10,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.background,
    gap: 10,
  },
  dateIconWrap: {
    width: 31,
    height: 31,
    borderRadius: 9,
    backgroundColor: colors.surface,
    alignItems: "center",
    justifyContent: "center",
  },
  dateIcon: {
    fontSize: 17,
    color: colors.primary,
    fontWeight: "800",
  },
  dateButtonText: {
    fontSize: 13,
    color: colors.text,
    fontWeight: "600",
    flex: 1,
  },
  dateChevron: {
    fontSize: 25,
    color: colors.textSecondary,
    marginRight: 3,
  },
  dateDisplay: {
    minHeight: 51,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 13,
    paddingHorizontal: 14,
    justifyContent: "center",
    backgroundColor: colors.background,
  },
  dateDisplayText: {
    fontSize: 13,
    color: colors.text,
  },
  pickerContainer: {
    marginTop: 8,
    padding: 9,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 14,
    backgroundColor: colors.surface,
  },
  pickerDoneButton: {
    alignSelf: "flex-end",
    backgroundColor: colors.primary,
    paddingHorizontal: 18,
    paddingVertical: 11,
    borderRadius: 10,
    marginTop: 8,
  },
  pickerDoneText: {
    color: "#FFFFFF",
    fontWeight: "900",
    fontSize: 12,
  },

  // Photo section
  photoInfoBanner: {
    flexDirection: "row",
    alignItems: "center",
    padding: 12,
    borderRadius: 14,
    backgroundColor: colors.background,
    borderWidth: 1,
    borderColor: colors.border,
    gap: 10,
    marginBottom: 13,
  },
  photoInfoIconWrap: {
    width: 39,
    height: 39,
    borderRadius: 12,
    backgroundColor: colors.surface,
    alignItems: "center",
    justifyContent: "center",
  },
  photoInfoIcon: {
    fontSize: 21,
  },
  photoInfoCopy: {
    flex: 1,
  },
  photoInfoTitle: {
    fontSize: 12,
    fontWeight: "900",
    color: colors.text,
  },
  photoInfoText: {
    fontSize: 10,
    lineHeight: 15,
    color: colors.textSecondary,
    marginTop: 4,
  },
  photoActions: {
    flexDirection: "row",
    gap: 10,
  },
  photoActionButton: {
    flex: 1,
    minHeight: 108,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 15,
    backgroundColor: colors.background,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 8,
    paddingVertical: 12,
  },
  photoActionIconWrap: {
    width: 42,
    height: 42,
    borderRadius: 14,
    backgroundColor: colors.surface,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 8,
  },
  photoActionIcon: {
    fontSize: 22,
  },
  photoActionText: {
    fontSize: 13,
    fontWeight: "900",
    color: colors.text,
  },
  photoActionSubtext: {
    fontSize: 10,
    color: colors.textSecondary,
    marginTop: 4,
  },
  photoCountRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 17,
    marginBottom: 10,
    gap: 8,
  },
  photoCountPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
    backgroundColor: colors.background,
    borderRadius: 9,
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  photoCountDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: "#21A875",
  },
  photoCount: {
    fontSize: 11,
    fontWeight: "900",
    color: colors.text,
  },
  photoHintSmall: {
    fontSize: 10,
    color: colors.textSecondary,
  },
  photoGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  photoTile: {
    position: "relative",
    borderRadius: 12,
    overflow: "hidden",
    backgroundColor: "#E9EAEC",
    borderWidth: 1,
    borderColor: colors.border,
  },
  thumbnailPressable: {
    flex: 1,
  },
  photoPreview: {
    width: "100%",
    height: "100%",
    backgroundColor: colors.background,
  },
  thumbnailNumberBadge: {
    position: "absolute",
    left: 5,
    bottom: 5,
    minWidth: 21,
    height: 21,
    paddingHorizontal: 5,
    borderRadius: 7,
    backgroundColor: "rgba(0,0,0,0.7)",
    alignItems: "center",
    justifyContent: "center",
  },
  thumbnailNumberText: {
    color: "#FFFFFF",
    fontSize: 10,
    fontWeight: "900",
  },
  removePhotoButton: {
    position: "absolute",
    top: 4,
    right: 4,
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: "rgba(15,15,15,0.84)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.72)",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 2,
  },
  removePhotoText: {
    color: "#FFFFFF",
    fontSize: 19,
    lineHeight: 21,
    fontWeight: "700",
  },
  addPhotoTile: {
    borderRadius: 12,
    borderWidth: 1.5,
    borderStyle: "dashed",
    borderColor: colors.primary,
    backgroundColor: colors.background,
    alignItems: "center",
    justifyContent: "center",
  },
  addPhotoIcon: {
    fontSize: 27,
    lineHeight: 31,
    fontWeight: "400",
    color: colors.primary,
  },
  addPhotoText: {
    marginTop: 3,
    fontSize: 10,
    fontWeight: "900",
    color: colors.primary,
    textAlign: "center",
  },
  noPhotosBox: {
    borderWidth: 1.5,
    borderColor: colors.border,
    borderStyle: "dashed",
    borderRadius: 15,
    padding: 22,
    marginTop: 12,
    alignItems: "center",
    backgroundColor: colors.background,
  },
  emptyPhotoIllustration: {
    width: 54,
    height: 54,
    borderRadius: 18,
    backgroundColor: colors.surface,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 11,
  },
  noPhotosIcon: {
    fontSize: 27,
    color: colors.textSecondary,
  },
  noPhotosText: {
    fontSize: 13,
    fontWeight: "900",
    color: colors.text,
  },
  noPhotosSubtext: {
    fontSize: 11,
    lineHeight: 17,
    color: colors.textSecondary,
    marginTop: 5,
    textAlign: "center",
  },

  // Submit area
  submitCard: {
    backgroundColor: colors.surface,
    borderRadius: 22,
    padding: 17,
    borderWidth: 1,
    borderColor: colors.border,
    marginTop: 1,
    shadowColor: "#172B4D",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 12,
    elevation: 2,
  },
  submitCardTop: {
    flexDirection: "row",
    alignItems: "center",
    gap: 11,
    marginBottom: 15,
  },
  submitIconWrap: {
    width: 41,
    height: 41,
    borderRadius: 14,
    backgroundColor: "rgba(35,170,112,0.12)",
    alignItems: "center",
    justifyContent: "center",
  },
  submitIcon: {
    color: "#16865C",
    fontSize: 21,
    fontWeight: "900",
  },
  submitCopy: {
    flex: 1,
  },
  submitTitle: {
    fontSize: 15,
    fontWeight: "900",
    color: colors.text,
  },
  submitSubtitle: {
    fontSize: 11,
    lineHeight: 16,
    color: colors.textSecondary,
    marginTop: 4,
  },
  primaryButton: {
    marginTop: 8,
    backgroundColor: colors.primary,
    borderRadius: 15,
    minHeight: 55,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 17,
    paddingVertical: 14,
    gap: 10,
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.18,
    shadowRadius: 9,
    elevation: 3,
  },
  primaryButtonText: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "900",
    textAlign: "center",
  },
  primaryButtonArrow: {
    color: "#FFFFFF",
    fontSize: 22,
    lineHeight: 24,
    fontWeight: "700",
  },
  secondaryButton: {
    marginTop: 10,
    minHeight: 50,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 15,
  },
  secondaryButtonText: {
    color: colors.text,
    fontSize: 13,
    fontWeight: "800",
  },
  securityNote: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 7,
    marginTop: 13,
  },
  securityNoteIcon: {
    fontSize: 12,
  },
  securityNoteText: {
    flex: 1,
    fontSize: 10,
    lineHeight: 16,
    color: colors.textSecondary,
  },
  footer: {
    textAlign: "center",
    fontSize: 9,
    fontWeight: "800",
    letterSpacing: 1,
    color: colors.textLight,
    marginTop: 22,
  },

  // Read-only summary
  statusBanner: {
    flexDirection: "row",
    alignItems: "center",
    gap: 11,
    padding: 14,
    borderRadius: 16,
    backgroundColor: "rgba(35,170,112,0.09)",
    borderWidth: 1,
    borderColor: "rgba(35,170,112,0.18)",
    marginBottom: 16,
  },
  statusBannerIcon: {
    width: 35,
    height: 35,
    borderRadius: 12,
    backgroundColor: "rgba(35,170,112,0.15)",
    alignItems: "center",
    justifyContent: "center",
  },
  statusBannerCheck: {
    color: "#16865C",
    fontSize: 18,
    fontWeight: "900",
  },
  statusBannerCopy: {
    flex: 1,
  },
  statusBannerTitle: {
    color: "#167B56",
    fontSize: 13,
    fontWeight: "900",
  },
  statusBannerText: {
    color: colors.textSecondary,
    fontSize: 11,
    lineHeight: 16,
    marginTop: 3,
  },
  detailsList: {
    borderTopWidth: 1,
    borderTopColor: colors.divider,
  },
  savedField: {
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: colors.divider,
  },
  savedFieldLabel: {
    color: colors.textSecondary,
    fontSize: 10,
    fontWeight: "800",
    marginBottom: 5,
  },
  savedFieldValue: {
    color: colors.text,
    fontSize: 14,
    lineHeight: 20,
    fontWeight: "600",
  },

  // Full-screen photo viewer
  viewerRoot: {
    flex: 1,
    backgroundColor: "#080808",
  },
  viewerSafeArea: {
    flex: 1,
    backgroundColor: "#080808",
  },
  viewerHeader: {
    minHeight: 62,
    paddingHorizontal: 16,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: "#333333",
  },
  viewerCloseButton: {
    width: 42,
    height: 42,
    borderRadius: 15,
    backgroundColor: "#242424",
    alignItems: "center",
    justifyContent: "center",
  },
  viewerCloseText: {
    color: "#FFFFFF",
    fontSize: 30,
    lineHeight: 34,
    fontWeight: "400",
  },
  viewerTitleWrap: {
    alignItems: "center",
  },
  viewerTitle: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "800",
  },
  viewerSubtitle: {
    color: "#8D8D8D",
    fontSize: 8,
    letterSpacing: 1.2,
    fontWeight: "900",
    marginTop: 4,
  },
  viewerHeaderSpacer: {
    width: 42,
    height: 42,
  },
  viewerImageArea: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
  },
  viewerImage: {
    width: "100%",
    height: "100%",
  },
  viewerNavButton: {
    position: "absolute",
    top: "45%",
    width: 43,
    height: 54,
    borderRadius: 15,
    backgroundColor: "rgba(40,40,40,0.85)",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 5,
  },
  viewerPrevious: {
    left: 10,
  },
  viewerNext: {
    right: 10,
  },
  viewerNavText: {
    color: "#FFFFFF",
    fontSize: 38,
    lineHeight: 42,
    fontWeight: "400",
  },
  viewerFooter: {
    minHeight: 70,
    paddingHorizontal: 18,
    paddingVertical: 11,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: "#333333",
    gap: 12,
  },
  viewerFooterText: {
    color: "#B8B8B8",
    fontSize: 11,
    flex: 1,
  },
  viewerRemoveButton: {
    paddingHorizontal: 14,
    paddingVertical: 11,
    borderRadius: 11,
    backgroundColor: "#302020",
    borderWidth: 1,
    borderColor: "#6D3A3A",
  },
  viewerRemoveText: {
    color: "#FFB7B7",
    fontSize: 12,
    fontWeight: "800",
  },
});